user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 768;
    # multi_accept on;
}

http {
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=static_cache:10m inactive=60m;
    proxy_cache_key "$scheme$request_method$host$request_uri";
    proxy_cache_valid 200 60m;

    add_header Cache-Status $upstream_cache_status;

    map $imgtype $origin_file {
        default desktop.jpg;
        desktopImg desktop.jpg;
        titleImg titleImg.png;
        small small.png;
    }


    server {
        listen 8080;

        location ~ ^/avatar/([0-9]+)$ {
            resolver 8.8.8.8;
            set $user_id $1;

            proxy_ssl_server_name on;
            proxy_set_header Host api.login.netdb.at;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_pass https://api.login.netdb.at/publicuser/$user_id/avatar;
        }

        location ~ ^/hub_images/(?<id>[A-Za-z0-9_-]+)/(?<imgtype>[A-Za-z0-9_-]+)/(?<w>\d+)x(?<h>\d+)\.(jpg|png)$ {
            resolver 8.8.8.8;
            set $sig "internal";
            set $src "https://image.hub.netdb.at/$id/$origin_file";

            proxy_ssl_server_name on;
            proxy_set_header Host imageproxy.netdb.at;
            proxy_hide_header Set-Cookie;

            proxy_pass https://imageproxy.netdb.at/$sig/rs:fit:$w:$h/plain/$src;
        }

        location ~ ^/hub_images/(?<id>\d+)/(?<file>[^/]+)$ {
            resolver 8.8.8.8;
            set $sig "internal";
            set $src "https://image.hub.netdb.at/$id/$file";

            proxy_ssl_server_name on;
            proxy_set_header Host imageproxy.netdb.at;

            proxy_pass https://imageproxy.netdb.at/$sig/plain/$src;
        }


        location /data/ {
            proxy_pass https://netdbhub.blob.core.windows.net;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_hide_header Access-Control-Allow-Origin;
            proxy_cache static_cache;
            proxy_cache_bypass $http_pragma;
            proxy_cache_revalidate on;
        }
    }
}